### PR TITLE
add plantuml snippet

### PR DESCRIPTION
**Pull request by robbyoconnor**
Add a snippet for [plantuml](http://plantuml.com)

### CODE REVIEW

**Comment by robbyoconnor** [comment]
bump

**Comment by AndreaCrotti** [comment]
That's cool but what I see from here
http://plantuml.com/emacs.html
that the actual syntax is not the one you used but something like

#+BEGIN_UML
  Alice -> Bob: Authentication Request
  Bob --> Alice: Authentication Response
#+END_UML

where is that syntax you used coming from?

**Comment by robbyoconnor** [comment]
This isn't for org-mode -- but for actual plantuml files -- what you described is an org-mode codeblock

**Comment by AndreaCrotti** [comment]
Well I said that because you placed the file in the org-mode directory, which means it's an org-mode snippet normally..

**Comment by robbyoconnor** [comment]
OH doh -- i'll fix it

**Comment by robbyoconnor** [comment]
Updated.

**Comment by AndreaCrotti** [comment]
Mm I think it's still wrong @robbyoconnor 
it's in the UML directory which means it would be activated automatically on uml-mode, which does not exist as far as I can see (while plantuml-mode does).

On top of that if it's not org-mode specific what is the #+BEGIN #+END thing for?

I don't see anything like that here http://plantuml.com/sequence.html#Basic_examples

**Comment by robbyoconnor** [comment]
Just fixed it

See http://plantuml.com/emacs.html

For org-babel   -- in short it's for org-mode UML blocks :)

**Comment by AndreaCrotti** [comment]
Yes I know what org-babel is ;)
Ok thanks I can merge it now

**Pull request merged**
