### PR TITLE
add arrow function snippets to js-mode (ES2015 syntax)

### PR DESCRIPTION
**Pull request by ybiquitous**
For details, see below link:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

partial fix for #134

### CODE REVIEW

**Comment by AndreaCrotti** [comment]
(Sorry for the double review)

**Comment by ybiquitous** [comment]
@AndreaCrotti Sure, I agree your idea.

I thought that to support any arguments was good idea, but this my solution is not simple and cool 😓 

OK, I will fix it 👍

**Comment by ybiquitous** [comment]
@AndreaCrotti I fixed via 58fb391. Please review again 🙏

**Comment by AndreaCrotti** [comment]
Great thanks @ybiquitous

**Pull request merged**
