### PR TITLE
added missing html snippets (recovered from yasnippet history)

### PR DESCRIPTION
**Pull request by julior**
The div tag was missing in the html snippets, and strangely there was a dov that looked like div. Probably a spelling issue.

### CODE REVIEW

**Comment by julior** [comment]
Added another commit with extra html snippets recovered from yasnippet history...

**Comment by AndreaCrotti** [comment]
So @julior the reason why they were removed is here
https://github.com/AndreaCrotti/yasnippet-snippets/pull/49

so in one way I agree they might be useful but on the other way emmet-mode is much better in this sense.
So I suggest you just try that instead, I would not recover these snippets ideally (but I can fix the typo of course).

**Comment by julior** [comment]
Hi @AndreaCrotti  that makes sense. I didn't know about emmet-mode, which definitively looks much better. Probably, it would be good to mention about this in the Readme file.

Thanks

**Comment by AndreaCrotti** [comment]
ok @julior I added more information in the README in this commit https://github.com/AndreaCrotti/yasnippet-snippets/commit/2baa8f24e7ea15cf5c0a418aeb493e432dd29f30
thanks

**Pull request closed without merging**
