### PR TITLE
Add PHP basic syntax (statement) for php-mode

### PR DESCRIPTION
**Pull request by zonuexe**
These are snippets of PHP's basic syntax.

### CODE REVIEW

**Comment by zonuexe** [comment]
@AndreaCrotti Could you review this PR?

**Comment by AndreaCrotti** [comment]
Here I am @zonuexe 
The snippets look really good, the only thing I would say is that you don't need to repeat the same code all over the place
(like `(file-name-nondirectory (file-name-sans-extension (or (buffer-file-name) (buffer-name (current-buffer)))))` )

And you can put the common stuff in a `.yas-setup.el` file in the php-mode directory.
See an example of how it's done for Python here.

 https://github.com/AndreaCrotti/yasnippet-snippets/blob/master/snippets/python-mode/.yas-setup.el

Other than that happy to merge it, thanks a lot!

**Comment by zonuexe** [comment]
@AndreaCrotti Thanks your review. I've been fixed it.

**Comment by AndreaCrotti** [comment]
Ok great thanks!

**Pull request merged**
