### PR TITLE
Fix indentation python-mode/function_docstring_numpy

### PR DESCRIPTION
**Pull request by servitoroftheoutergods**
the indentation was wrong, using only one space instead of 4.

### CODE REVIEW

**Comment by npostavs** [comment]
But what about the `# NOTE: Use minimum indentation, because Emacs 25+ doesn't dedent docstrings.`? (I'm pretty sure I wrote that note, but I don't recall the exact details right now)

**Comment by servitoroftheoutergods** [comment]
the indentation was not a multiple of four.
the snippet  function_docstring_numpy has the correct indentation.
function_docstring is now with the same indentation.

**Comment by servitoroftheoutergods** [comment]
I use Emacs 25.3.1, and the docstring is working.

**Comment by npostavs** [comment]
> I use Emacs 25.3.1, and the docstring is working.

Did you check with `python-indent-offset` set to `2` (as described in joaotavora/yasnippet#750)?

**Comment by servitoroftheoutergods** [comment]
```

Result when using ‘python-indent-offset’ = 1:

def name():
 """
 
 """
 
Can’t guess python-indent-offset, using defaults: 2


Result when using ‘python-indent-offset’ = 2:

def name():
  """
  
  """
  
Can’t guess python-indent-offset, using defaults: 3


Result when using ‘python-indent-offset’ = 3:

def name():
   """
   
   """
   
Can’t guess python-indent-offset, using defaults: 4


Result when using ‘python-indent-offset’ = 4:

def name():
    """
    
    """
    
Can’t guess python-indent-offset, using defaults: 5


Result when using ‘python-indent-offset’ = 5:

def name():
     """
     
     """
     
Can’t guess python-indent-offset, using defaults: 6


Result when using ‘python-indent-offset’ = 6:

def name():
      """
      
      """
      
Can’t guess python-indent-offset, using defaults: 7


Result when using ‘python-indent-offset’ = 7:

def name():
       """
       
       """
       
Can’t guess python-indent-offset, using defaults: 8


Result when using ‘python-indent-offset’ = 8:

def name():
        """
        
        """

```

**Comment by servitoroftheoutergods** [comment]
:O plot twist, function_docstring_numpy is wrong.

**Comment by servitoroftheoutergods** [comment]
thanks @npostavs  for the patience ^^ .

**Pull request merged**
