### PR TITLE
Add elixir-ts-mode

### PR DESCRIPTION
**Pull request by wkirschbaum**
elixir-ts-mode is a new major mode for the Elixir programming language with tree-sitter support: https://github.com/wkirschbaum/elixir-ts-mode

This mode is in the process of being submitted to emacs master and will probably be submitted to MELPA in the next week.

### CODE REVIEW

**Comment by wkirschbaum** [comment]
Hi @petergardfjall , is there anything else required for this to be merged? I am not sure if I missed something.

**Comment by petergardfjall** [comment]
> Hi @petergardfjall , is there anything else required for this to be merged? I am not sure if I missed something.

I don't think so, I pretty much copied this one when I submitted the pr for `go-ts-mode`. 😄

**Comment by wkirschbaum** [comment]
@AndreaCrotti is there a chance this can be merged?

**Comment by AndreaCrotti** [comment]
Yes sorry done @wkirschbaum

**Comment by wkirschbaum** [comment]
thank you! :)

**Pull request merged**
