### PR TITLE
add 'try...catch' statement snippet to js-mode

### PR DESCRIPTION
**Pull request by ybiquitous**
For details, see below link:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

### CODE REVIEW

**Comment by AndreaCrotti** [comment]
Looks good @ybiquitous 
Only thing I would say is that the exception caught is always called `e`?
Is that a widespread convention?

**Comment by ybiquitous** [comment]
@AndreaCrotti Umm..., I don't have exact statistics, but I see that these are commonly used:

- `err`
  - [Google](https://google.github.io/styleguide/jsguide.html#formatting-nonempty-blocks)
  - [Node.js](https://nodejs.org/api/errors.html#errors_error_propagation_and_interception)
  - [w3schools](https://www.w3schools.com/js/js_errors.asp)
- `e`
  - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch)
  - [Microsoft](https://docs.microsoft.com/en-us/scripting/javascript/reference/try-dot-dot-dot-catch-dot-dot-dot-finally-statement-javascript)
- others...
  - `error`
  - `ex`

Maybe recently, `err` seems more popular than `e`. But I can use either.

**Comment by AndreaCrotti** [comment]
I would go with `err` and possibly still make it customizable (so something like `${3:err}`, or whatever index you get to).
Thanks!

**Comment by ybiquitous** [comment]
@AndreaCrotti 
I think that `${3:err}` is too customizable, so I will apply `err` (more popular). It's OK?

**Comment by AndreaCrotti** [comment]
Yeah ok let's do `err`, thanks

**Comment by ybiquitous** [comment]
@AndreaCrotti Thanks a lot! 😆

**Pull request merged**
