### PR TITLE
Added doxygen-mode for cc-mode 

### PR DESCRIPTION
**Pull request by henriquenj**
This pull request adds three new snippets for doxygen-like documentation following the manual available at http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html.

Comments are welcome.

### CODE REVIEW

**Comment by henriquenj** [comment]
This is my first pull request using github, is there a way I could get rid of these merge commits so it won't pollute your log? I was merely keeping my fork updated.

**Comment by npostavs** [comment]
> I was merely keeping my fork updated.

You should do this with rebase instead of merge. The pull request can be updated by additional pushes to the branch (your `master` in this case), including `push --force` which remove commits.

**Comment by henriquenj** [comment]
Thank you for the help, I'll use this strategy next time.

After I pushed my branch without the merge commits (I had remove my own commits as well), github closed the the pull request. Not a problem, I submitted a new one!

**Comment by npostavs** [comment]
> After I pushed my branch without the merge commits (I had remove my own commits as well), github closed the the pull request

Oh, I guess if you set it to 0 commits it thinks you're done.

**Pull request closed without merging**
