### PR TITLE
Add a generic org src block

### PR DESCRIPTION
**Pull request by r-darwish**

### CODE REVIEW

**Comment by AndreaCrotti** [comment]
Should we not use the new mechanism `C-c C-,` now for this purpose @r-darwish ?

**Comment by r-darwish** [comment]
I personally don't like the idea of org inventing its own snippets mechanism. I use yasnippets in almost every mode so for me it makes sense to keep using it even in org mode.

**Comment by AndreaCrotti** [comment]
Yeah ok makes sense, just not sure about the key, in another PR it was added with "<src" which maybe is better since it's consistent to how org used to work, what do you think @r-darwish ?

**Comment by r-darwish** [comment]
I'm okay with `<src`

**Comment by AndreaCrotti** [comment]
ok I'll close this then and I'll merge the other proposal

**Pull request closed without merging**
