### PR TITLE
rewrite 'class' and 'constructor' for ES2015 syntax in js-mode

### PR DESCRIPTION
**Pull request by ybiquitous**
partial fix for #134

For details, see [Classes - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes).

### CODE REVIEW

**Comment by ybiquitous** [comment]
This PR breaks compatibility, but ES2015 (ES6) becomes very familiar recently, so I think that it will not cause big problems.

What do you think about this? Please I hope any feedbacks!

**Comment by AndreaCrotti** [comment]
Well I'm not sure it's worth to break backward compatibility @ybiquitous 
I'm not an expert but lots of people are still not writing ES6 all the time right?
Could we not simply add another snippet and leave the original one as it is?

Another option is to have both snippets there with the same key, in that case yasnippet simply provides you with the option to choose which one you need.

**Comment by ybiquitous** [comment]
@AndreaCrotti 
I pushed 5c214f9 to keep compatibility. Please review again 🙏

**Comment by AndreaCrotti** [comment]
Cool thanks @ybiquitous

**Pull request merged**
