### PR TITLE
Add ipython embed snippet

### PR DESCRIPTION
**Pull request by halfcrazy**
Most time i use ipython embed to debug.

### CODE REVIEW

**Comment by AndreaCrotti** [comment]
thanks @halfcrazy 
I don't normally use this for debugging, but more ipdb or pdbpp.
I'm not sure that's what really ipython.embed is for exactly, so maybe I would just remove it from the "debug" group..

**Comment by halfcrazy** [comment]
@AndreaCrotti It can open an interactive ipython shell when execute to that line. In the interactive shell, you have the current context and you can use ipython auto-complete feature to debug.

**Comment by AndreaCrotti** [comment]
yes sure I know, I'm just saying that's not what it was for imho.
It's more to actual embed an interactive interpreter inside your application very easily, not really just for debugging.
But anyway I don't mind too much, but would be better to remove the "group: debug" line for me

**Comment by halfcrazy** [comment]
@AndreaCrotti ping

**Comment by AndreaCrotti** [comment]
Merged thanks

**Pull request merged**
