### PR TITLE
Add applescript snippets from apples-mode

### PR DESCRIPTION
**Pull request by suzume**
apples-mode had snippets that were not in this repository:
https://github.com/tequilasunset/apples-mode

### CODE REVIEW

**Comment by AndreaCrotti** [comment]
Should generally ask permission to the author before taking snippets from other repositories @suzume 
Did you ask already maybe?

**Comment by suzume** [comment]
The original repository has been inactive for 6 years, right after the original code has been committed. I've sent a pull request to make the code compatible with recent versions of OSX but have not yet received any answer. I've also sent a mail to the address documented in the source, no reaction too.

**Comment by suzume** [comment]
@AndreaCrotti is there anything else I need to do to have that request considered ?

**Comment by AndreaCrotti** [comment]
Here I am sorry, yes it's fine I think we it's fine to copy them over in this particular case.
Thanks!

**Pull request merged**
