### PR TITLE
Move some C/++ specific stuff to its own subdir

### PR DESCRIPTION
**Pull request by npostavs**
See https://github.com/joaotavora/yasnippet/issues/580#issuecomment-338540349

### CODE REVIEW

**Comment by SteveJobzniak** [comment]
Thanks! Very useful, but I doubt that `c-lang-mode` will be accepted since a future mode may use that name. I bet @AndreaCrotti will want another name for this reorganizing. Something without `-mode` at all I guess...

**Comment by AndreaCrotti** [comment]
Ah nice @npostav 
so I think it's fine but yes maybe `c-lang-mode` suggests that there should be a `c-lang-mode` which actually doesn't exist.
So maybe something like `c-lang-common` instead? (Or I'm open to other suggestions of course)

**Comment by SteveJobzniak** [comment]
I like `c-lang-common` a lot.

**Comment by npostavs** [comment]
> I like c-lang-common a lot. So +1.

`c-lang-common` it is.

**Comment by AndreaCrotti** [comment]
Great thanks

**Pull request merged**
