### PR TITLE
Support typescript-mode

### LINKED ISSUE #139: Add typescript snipets
Emacs (Spacemacs/develop) has decent typescript support. The only missing thing for me is snippeting(snipping?).

### PR DESCRIPTION
**Pull request by ybiquitous**
This fixes #139.

For more details, see <https://github.com/ananthakumaran/typescript.el>.

### CODE REVIEW

**Comment by AndreaCrotti** [comment]
Hi @ybiquitous thanks for your contribution, but just to clarify, doesn't it just mean that all the JS snippets will be available to typescript mode  with this change?
It doesn't really add any specific typescript specific snippets right?

**Comment by ybiquitous** [comment]
Hi. @AndreaCrotti 
As you pointed out, this PR does not add TypeScript specific snippets. 

However, since TypeScript is a superset of JavaScript, all JavaScript snippets can also be used in TypeScript.

I wanted to use the TypeScript snippet with minimal effort first, so I just simply inherit JavaScript snippets in this PR.

**Comment by AndreaCrotti** [comment]
Yes sure fine, makes sense 👍

**Comment by ybiquitous** [comment]
Thank you for understanding! 😸

**Pull request merged**
